/* eslint-disable max-lines -- Large data file with names */
export const names = [
  'Adam Baum',
  'Adam Zapel',
  'Ader Titsoff',
  'Ahmed Adoudi',
  'Al Bino',
  'Al Coholic',
  'Al Dente',
  'Al Fresco',
  'Ali Gaither',
  'Ali Katt',
  'Aliver Wood',
  'Alotta Fagina',
  'Amanda Hudgenkiss',
  'Amanda Hump',
  'Amanda Lay',
  'Amanda Lick',
  'Amanda Lynn',
  'Amanda Mount',
  'Amanda Poker',
  'Amber Green',
  'Amy Rack',
  'Andy Cornholder',
  'Andy Feltherbush',
  'Andy Friese',
  'Angelina Cage',
  'Anita Bajay',
  'Anita Bajaynow',
  'Anita Bath',
  'Anita Bathe',
  'Anita Bohn',
  'Anita Dick',
  'Anita Dickenme',
  'Anita Dump',
  'Anita Friske',
  'Anita Goodman',
  'Anita Hanjaab',
  'Anita Hanke',
  'Anita Hardcok',
  'Anita Head',
  'Anita Hoare',
  'Anita Job',
  'Anita Knapp',
  'Anita Lay',
  'Anita Little',
  'Anita Manbow',
  'Anita Mandalay',
  'Anita Mann',
  'Anita Naylor',
  'Anita Plummer',
  'Anna Conda',
  'Anna Fender',
  'Anna Graham',
  'Anna Prentice',
  'Anna Recksiek',
  'Anna Sasin',
  'Anne Teak',
  'Annette Curtain',
  'Annie Howe',
  'Annie Matter',
  'Annie Position',
  'Anya Neeze',
  'April May',
  'April Schauer',
  'Aretha Holly',
  'Armand Hammer',
  'Arsema Wholl',
  'Art Major',
  'Art Painter',
  'Art Sellers',
  'Babba Lon',
  'Barb Dwyer',
  'Barbara Seville',
  'Barry Cade',
  'Bea Lowe',
  'Bea Minor',
  'Beau Archer',
  'Beau Kaye',
  'Beau Tye',
  'Ben Derhover',
  'Ben Dover',
  'Ben Down',
  'Ben Marcata',
  'Benoit Bawles',
  'Bess Eaton',
  'Betty Drilser',
  'Betty Humpter',
  'Biff Wellington',
  'Bill Board',
  'Bill Ding',
  'Bill Dollar',
  'Bill Foldes',
  'Bill Loney',
  'Billy Rubin',
  'Bob Apple',
  'Bob Katz',
  'Bob Loblaw',
  'Bobbie Dong',
  'Bona Jones',
  'Bonnie Beaver',
  'Brad Hammer',
  'Brandon Cattell',
  'Brandon Irons',
  'Bridget Biffins',
  'Brighton Early',
  'Brock Lee',
  'Brooke Trout',
  'Buck Nekkid',
  'Bud Light',
  'Bud Wieser',
  'Bum Smith',
  'Burt Banus',
  'Buster Cherry',
  'Buster Hyman',
  'Bustie Barnes',
  'Caba Osse',
  'Cam Payne',
  'Candace Spencer',
  'Candy Barr',
  'Candy Baskett',
  'Candy Kane',
  'Candy Sweet',
  'Cara Sterio',
  'Cara Van',
  'Carrie Dababi',
  'Carrie Oakey',
  'Casey Macy',
  'Charity Case',
  'Charles Chode',
  'Charlie Sangels',
  'Cheri Pitts',
  'Cherry Bombe',
  'Chip Munk',
  'Chip Stone',
  'Chris Coe',
  'Chris Cross',
  'Chris P. Bacon',
  'Clee Torres',
  'Cliff Mountain',
  'Cole Ostamie',
  'Colin Forsecs',
  'Connie Lingus',
  'Constance Noring',
  'Cookie Chonch',
  'Corey Ander',
  'Count Dunn',
  'Count Orff',
  'Coyne Flatt',
  'Craven Moorehead',
  'Crystal Ball',
  'Crystal Glass',
  'Crystal Metheney',
  'Crystal Snow',
  'Curley Pubes',
  'Dan Deline',
  'Dan Druff',
  'Dan Saulnight',
  'Dang Lin-Wang',
  'Darren Deeds',
  'Daryl B. Payne',
  'Daryl Rhea',
  'Dean Gulberry',
  'Dear Beloved',
  'Dee Major',
  'Dick Bender',
  'Dick Burns',
  'Dick Bush',
  'Dick Dangler',
  'Dick Face',
  'Dick Finder',
  'Dick Getzoff',
  'Dick Handler',
  'Dick Hardigan',
  'Dick Head',
  'Dick Hertz',
  'Dick Hunter',
  'Dick Hyman',
  'Dick Johnson',
  'Dick Long',
  'Dick Mussell',
  'Dick Myaz',
  'Dick Nose',
  'Dick Pole',
  'Dick Pound',
  'Dick Raasch',
  'Dick Ramdass',
  'Dick Rasch',
  'Dick Swett',
  'Dick Tapper',
  'Dick Tator',
  'Dick Trickle',
  'Dick Wood',
  'Dickson Yamada',
  'Dilbert Pickles',
  'Dill Doe',
  'Dinah Soares',
  'Dixie Normous',
  'Dixie Rect',
  'Dick Butz',
  'Doris Schutt',
  'Doug Graves',
  'Doug Hole',
  'Doug Witherspoon',
  'Douglas Furr',
  'Drew Peacock',
  'Drew Peanoze',
  'Duane Pipe',
  'Dusty Carr',
  'Dusty Rhodes',
  'Dusty Sandman',
  'Easton West',
  'Eaton Beaver',
  'Eaton Wright',
  'Eddie Current',
  'Edna May',
  'Eileen Dover',
  'Eileen Ulick',
  'Ella Vader',
  'Emma Royds',
  'Eric Shinn',
  'Estelle Hertz',
  'Evan Keel',
  'Faith Christian',
  'Fanny Hertz',
  'Fanny O’Rear',
  'Fanny Turner',
  'Ferris Wheeler',
  'Flint Sparks',
  'Fluffy Cookie',
  'Fonda Dicks',
  'Ford Parker',
  'Forrest Green',
  'Foster Child',
  'Frank Enstein',
  'Gae Hooker',
  'Gail Force',
  'Gail Storm',
  'Garret Grundel',
  'Gaye Barr',
  'Gaye Jolly',
  'Gazzy Colon',
  'Gene Poole',
  'Geraldine Gooch',
  'Gil Fish',
  'Ginger Rayl',
  'Ginger Snapp',
  'Ginger Vitus',
  'Gonad Jones',
  'Hairy Poppins',
  'Hamilton Burger',
  'Harden Thicke',
  'Harold Assman',
  'Harry Azcrac',
  'Harry Baals',
  'Harry Beard',
  'Harry Beaver',
  'Harry Butts',
  'Harry Chest',
  'Harry Cox',
  'Harry Dangler',
  'Harry Hooker',
  'Harry Johnson',
  'Harry Legg',
  'Harry Lipp',
  'Harry Peters',
  'Harry Pitts',
  'Harry Rump',
  'Harry Sachs',
  'Hazle Nutt',
  'Heidi Clare',
  'Helen Back',
  'Helen Waite',
  'Helen Wiells',
  'Herb Farmer',
  'Holly Day',
  'Holly McRell',
  'Holly Wood',
  'Homer Sexual',
  'Honey Bee',
  'Howie Doohan',
  'Hugh Jass',
  'Hugh Jorgan',
  'I.P. Freely',
  'Ileane Wright',
  'Ilene South',
  'Ima Hogg',
  'Ima Weiner',
  'Iona Corolla',
  'Iona Ford',
  'Iona Frisbee',
  'Iona Stonehouse',
  'Isadore Bell',
  'Ivan Oder',
  'Ivana Likyu',
  'Ivana Mandic',
  'Ivana Tinkle',
  'Ivy Leage',
  'Jack Goff',
  'Jack Haas',
  'Jack Hammer',
  'Jack Hoff',
  'Jack Knoff',
  'Jack Pott',
  'Jack Tupp',
  'Jack Zubra',
  'Jacklyn Hyde',
  'Jacques Strap',
  'Jasmine Rice',
  'Jay Walker',
  'Jean Poole',
  'Jed Dye',
  'Jenny Tayla',
  'Jenny Tull',
  'Jerry Atrick',
  'Jim Laucher',
  'Jim Shorts',
  'Jim Shu',
  'Jim Sox',
  'Jo King',
  'Joe Kerr',
  'John Thomas',
  'Johnny Boner',
  'Jordan Rivers',
  'Joy Kil',
  'Joy Rider',
  'June Bugg',
  'Justin Case',
  'Justin Hale',
  'Justin Sane',
  'Kandi Apple',
  'Kareem O’Weet',
  'Karl Kuder',
  'Katelyn Kwif',
  'Kay Bull',
  'Kelly Green',
  'Ken Dahl',
  'Kenny Dewitt',
  'Kenny Penny',
  'Kenya Dewit',
  'Kerry Oki',
  'Kitty Carr',
  'Kitty Katz',
  'Lance Boyle',
  'Lance Butts',
  'Lance Lyde',
  'Laura Norder',
  'Lee Keybum',
  'Lee Keyrear',
  'Lee Nover',
  'Leigh King',
  'Leo Tarred',
  'Les Moore',
  'Les Payne',
  'Les Plack',
  'Levon Coates',
  'Lily Pond',
  'Lina Ginster',
  'Lindsay Doyle',
  'Lisa Carr',
  'Lisa Ford',
  'Lisa Honda',
  'Liv Good',
  'Liv Long',
  'Lois Price',
  'Lon Moore',
  'Lou Briccant',
  'Lou Pole',
  'Lou Sirr',
  'Lou Zar',
  'Lucy Fer',
  'Luke Atmyass',
  'Luke Warm',
  'Macon Paine',
  'Madka Owdiseez',
  'Manny Kinn',
  'Marcus Mangina',
  'Marion Money',
  'Mark Skid',
  'Mark Spot',
  'Marlon Fisher',
  'Marsha Dimes',
  'Marsha Mellow',
  'Marshall Law',
  'Martha Fokker',
  'Marty Graw',
  'Mary Christmas',
  'Mary Juana',
  'Master Bates',
  'Matt Tress',
  'Max Little',
  'Max Power',
  'May Day',
  'May Furst',
  'May Tutchem',
  'Maya Buttreeks',
  'Maya Taint',
  'Mel Keetehts',
  'Melba Crisp',
  'Mia Hamm',
  'Michael Toris',
  'Mike Easter',
  'Mike Hunt',
  'Mike Raffone',
  'Mike Reinhart',
  'Mike Rotch',
  'Mike Rotchburns',
  'Mike Stand',
  'Mike Sweeney',
  'Miles Vart',
  'Milly Graham',
  'Missy Sippy',
  'Misty Waters',
  'Mo Lestor',
  'Moe DeGrasse',
  'Moe Dick',
  'Moe Ron',
  'Molly Kuehl',
  'Mona Lott',
  'Monica Monica',
  'Morey Bund',
  'Myles Long',
  'Nadia Seymour',
  'Nat Sass',
  'Neil Crouch',
  'Neil Down',
  'Neil McNeil',
  'Nip Pulle',
  'Noah Lott',
  'Noah Riddle',
  'Norma Scock',
  'Norma Stits',
  'Normous Peters',
  'Olive Branch',
  'Olive Green',
  'Olive Hoyl',
  'Olive Yew',
  'Oliver Closeoff',
  'Oliver Klozoff',
  'Oliver Sutton',
  'Ollie Tabooger',
  'Ophelia Payne',
  'Oren Jellow',
  'Orson Carte',
  'Oscar Ruitt',
  'Otto Carr',
  'Otto Graf',
  'Owen Big',
  'Owen Cash',
  'Owen Moore',
  'Paige Turner',
  'Parker Carr',
  'Pat Downe',
  'Pat Hiscock',
  'Pat McCann',
  'Pat Myaz',
  'Patience Wait',
  'Patton Cox',
  'Patty Meltt',
  'Paul Mussy',
  'Paula Putang',
  'Peg Legge',
  'Penny Nichols',
  'Penny Wise',
  'Pepe Roni',
  'Pete Moss',
  'Peter Johnson',
  'Peter Pantz',
  'Peter Peed',
  'Peter Skeeter',
  'Peter Wacko',
  'Phil Accio',
  'Phil Bowles',
  'Phil Down',
  'Phil Graves',
  'Phil McKracken',
  'Phil Rupp',
  'Phil Wright',
  'Phillip Bagg',
  'Pierce Cox',
  'Pierce Deere',
  'Pierce Hart',
  'Pierre Pants',
  'Pokie Bitts',
  'Polly Ester',
  'Priti Manek',
  'Randy Guy',
  'Randy Lover',
  'Raney Schauer',
  'Ray Gunn',
  'Ray Zenz',
  'Raynor Schein',
  'Reginald Soles',
  'Reid Enright',
  'Rex Easley',
  'Rex Sean',
  'Rhea Curran',
  'Rhea Rhend',
  'Rhoda Booke',
  'Rhoda Hotte',
  'Rich Feller',
  'Rich Guy',
  'Rich Kidd',
  'Rich Mann',
  'Richard Chopp',
  'Richard Mipple',
  'Rick O’Shea',
  'Rick Shaw',
  'Rip Torn',
  'Rita Booke',
  'Rita Buch',
  'Rita Story',
  'Rob Banks',
  'Robert',
  'Robin Banks',
  'Robin Feathers',
  'Robin Money',
  'Roch Myaz',
  'Roman Holiday',
  'Ron Chee',
  'Rose Bush',
  'Rose Gardner',
  'Rowan Boatman',
  'Royal Payne',
  'Rufus Roofie',
  'Russell Leeves',
  'Russell Sprout',
  'Rusty Blades',
  'Rusty Bridges',
  'Rusty Carr',
  'Rusty Dorr',
  'Rusty Fender',
  'Rusty Fossat',
  'Rusty Irons',
  'Rusty Keyes',
  'Rusty Nail',
  'Rusty Steele',
  'Ryan Carnation',
  'Ryan Coke',
  'Sal Ami',
  'Sal Minella',
  'Sally Forth',
  'Sam Manilla',
  'Sam Tata',
  'Sandy Brown',
  'Sarah Bellum',
  'Sawyer Dickey',
  'Seth Poole',
  'Seymour Bush',
  'Seymour Butz',
  'Seymour Johnson',
  'Shanda Lear',
  'Sharon Fillerup',
  'Sharon Needles',
  'Sharon Weed',
  'Sheeza Freak',
  'Sheila Blige',
  'Skip Dover',
  'Skip Roper',
  'Skip Stone',
  'Sonny Day',
  'Stan Still',
  'Sue Flay',
  'Sue Jeu',
  'Sue Render',
  'Sue Ridge',
  'Sue Yu',
  'Suky Nookie',
  'Summer Day',
  'Suzie Tang',
  'Sy Burnette',
  'Tad Moore',
  'Tad Pohl',
  'Tamara Knight',
  'Tanya Hyde',
  'Tara Cherry',
  'Tate Painter',
  'Teresa Green',
  'Terry Achey',
  'Terry Bull',
  'Tess Steckle',
  'Tiffany Box',
  'Tim Burr',
  'Tish Hughes',
  'Trina Forest',
  'Tush Johnson',
  'Ty Knotts',
  'Unda Boub',
  'Ura Snotball',
  'Urich Hunt',
  'Vaja Jay',
  'Viola Solo',
  'Vye Agra',
  'Vye Brator',
  'Walter Melon',
  'Wanda Rinn',
  'Wanna Hickey',
  'Warren Peace',
  'Waylon Smithers',
  'Wayne Kerr',
  'Willie Eetmioutt',
  'Willie Hardigan',
  'Willie Layer',
  'Willie Leak',
  'Willie Stroker',
  'Wilma Dickfit',
  'Wilma Fingerdoo',
  'Woody Forrest',
  'Yuri Nator',
] as const

export const countries = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Austria',
  'Azerbaijan',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada, eh?',
  'Central African Republic',
  'Chad',
  'Channel Islands',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo',
  'Costa Rica',
  "Côte d'Ivoire",
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'DR Congo',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Faeroe Islands',
  'Finland',
  'France',
  'French Guiana',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Holy See',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Isle of Man',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macao',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Mauritania',
  'Mauritius',
  'Mayotte',
  'Mexico',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nepal',
  'Netherlands',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North Korea',
  'North Macedonia',
  'Norway',
  'Oman',
  'Pakistan',
  'Panama',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Réunion',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Helena',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent and the Grenadines',
  'San Marino',
  'Sao Tome & Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Somalia',
  'South Africa',
  'South Korea',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'State of Palestine',
  'Sudan',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'The Bahamas',
  'Timor-Leste',
  'Togo',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  '"United" Kingdom',
  'Trumpmenistan',
  'Uruguay',
  'Uzbekistan',
  'Venezuela',
  'Vietnam',
  'Western Sahara',
  'Yemen',
  'Zambia',
  'Zimbabwe',
] as const
